export const pasarData = [
  {
    id: 1,
    nama: "Pasar Bogor",
    lokasi: "Jalan Suryakencana 18216",
    kota: "Bogor",
    gambar:
      "https://static.republika.co.id/uploads/images/inpicture_slide/036481400-1688106898-830-556.jpg",
    JamOperasional: "07:00 - 11:00",
    GoogleMaps: "asdisadidsi",
    tipe: "pasar",
  },
  {
    id: 2,
    nama: "Pasar Anyar",
    lokasi: "Jalan Dewi Sartika No. 10",
    kota: "Bogor",
    gambar: "https://example.com/pasar-anyar.jpg",
    JamOperasional: "06:00 - 12:00",
    GoogleMaps: "link_google_maps_pasar_anyar",
    tipe: "minimarket",
  },
  {
    id: 3,
    nama: "Pasar Ciawi",
    lokasi: "Jalan Raya Ciawi No. 15",
    kota: "Bogor",
    gambar: "https://example.com/pasar-ciawi.jpg",
    JamOperasional: "05:30 - 13:00",
    GoogleMaps: "link_google_maps_pasar_ciawi",
    tipe: "pasar",
  },
  {
    id: 4,
    nama: "Pasar Kebon Kembang",
    lokasi: "Jalan Merdeka No. 45",
    kota: "Bogor",
    gambar: "https://example.com/pasar-kebon-kembang.jpg",
    JamOperasional: "06:00 - 14:00",
    GoogleMaps: "link_google_maps_pasar_kebon_kembang",
    tipe: "pasar",
  },
  {
    id: 5,
    nama: "Pasar Cibinong",
    lokasi: "Jalan Raya Cibinong No. 20",
    kota: "Bogor",
    gambar: "https://example.com/pasar-cibinong.jpg",
    JamOperasional: "05:00 - 13:00",
    GoogleMaps: "link_google_maps_pasar_cibinong",
    tipe: "pasar",
  },
  {
    id: 6,
    nama: "Pasar Gunung Batu",
    lokasi: "Jalan Gunung Batu No. 7",
    kota: "Bogor",
    gambar: "https://example.com/pasar-gunung-batu.jpg",
    JamOperasional: "06:30 - 12:30",
    GoogleMaps: "link_google_maps_pasar_gunung_batu",
    tipe: "pasar",
  },
  {
    id: 7,
    nama: "Pasar Jambu Dua",
    lokasi: "Jalan Pajajaran No. 100",
    kota: "Bogor",
    gambar: "https://example.com/pasar-jambu-dua.jpg",
    JamOperasional: "07:00 - 11:30",
    GoogleMaps: "link_google_maps_pasar_jambu_dua",
    tipe: "pasar",
  },
  {
    id: 8,
    nama: "Pasar Sindangbarang",
    lokasi: "Jalan Sindangbarang No. 25",
    kota: "Bogor",
    gambar: "https://example.com/pasar-sindangbarang.jpg",
    JamOperasional: "05:30 - 12:00",
    GoogleMaps: "link_google_maps_pasar_sindangbarang",
    tipe: "pasar",
  },
  {
    id: 9,
    nama: "Pasar Sindangbarang",
    lokasi: "Jalan Sindangbarang No. 25",
    kota: "Bogor",
    gambar: "https://example.com/pasar-sindangbarang.jpg",
    JamOperasional: "05:30 - 12:00",
    GoogleMaps: "link_google_maps_pasar_sindangbarang",
    tipe: "pasar",
  },
];
